// IMPORTANT: Start your code on the 2nd line
pref("app.update.auto", false);
pref("app.update.interval", 10000000);
pref("browser.aboutwelcome.enabled", false);
pref("browser.defaultbrowser.notificationbar", false);
pref("browser.reader.detectedFirstArticle", false);
pref("browser.shell.checkDefaultBrowser", false);
pref("browser.tabs.warnOnClose", false);
pref("browser.usedOnWindows10", true);
pref("browser.warnOnQuit", false);
pref("datareporting.healthreport.service.firstRun", false);
pref("dom.webnotifications.enabled", false);
pref("extensions.htmlaboutaddons.recommendations.enabled", false);
pref("extensions.update.enabled", false);
pref("identity.fxaccounts.enabled", false);
pref("image.animation_mode", "none");
pref("startup.homepage_override_url", "");
pref("toolkit.telemetry.reportingpolicy.firstRun", false);
pref("xpinstall.signatures.required", false);
